### ISSUE TITLE
Can't find security groups

### ISSUE THREAD

**Issue by wilsonhipolito** [chaordic/tiopatinhas#7]
Hi guys!

I'm trying to use tiopatinhas on my ASG but it returns an error with security groups:
```
[root:~/tiopatinhas/tp #]python tp.py -g ASG-nginx-images-prod-20160316 -v
2016-04-28 23:38:28,338 ASG-nginx-images-prod-20160316 INFO Starting Tio Patinhas
2016-04-28 23:38:28,339 ASG-nginx-images-prod-20160316 DEBUG Refreshing state...
2016-04-28 23:38:30,432 ASG-nginx-images-prod-20160316 DEBUG Current candidate for target instances: 1.0
2016-04-28 23:38:30,432 ASG-nginx-images-prod-20160316 DEBUG >> guess_target(): changed target from 0 to 1.0
2016-04-28 23:38:30,432 ASG-nginx-images-prod-20160316 INFO >> refresh(): autoscale instance count changed from None to 1
2016-04-28 23:38:30,432 ASG-nginx-images-prod-20160316 DEBUG *** Current state:
2016-04-28 23:38:30,433 ASG-nginx-images-prod-20160316 DEBUG Managed by Autoscale: 1
2016-04-28 23:38:30,433 ASG-nginx-images-prod-20160316 DEBUG Managed by TP: 0
2016-04-28 23:38:30,433 ASG-nginx-images-prod-20160316 DEBUG Target: 1.0
2016-04-28 23:38:30,433 ASG-nginx-images-prod-20160316 DEBUG Live:
2016-04-28 23:38:30,433 ASG-nginx-images-prod-20160316 DEBUG Emergency:
2016-04-28 23:38:30,433 ASG-nginx-images-prod-20160316 DEBUG LB Unhealthy:
2016-04-28 23:38:30,433 ASG-nginx-images-prod-20160316 DEBUG Checking if needs to launch emergency instances
2016-04-28 23:38:30,433 ASG-nginx-images-prod-20160316 DEBUG Checking if there's any emergency instance to replace
2016-04-28 23:38:30,433 ASG-nginx-images-prod-20160316 DEBUG Checking if it needs to buy spot instances
2016-04-28 23:38:30,488 boto ERROR 400 Bad Request
2016-04-28 23:38:30,488 boto ERROR <?xml version="1.0" encoding="UTF-8"?>
<Response><Errors><Error><Code>InvalidGroup.NotFound</Code><Message>The security group 'sg-270fa542' does not exist</Message></Error></Errors><RequestID>718987da-03bd-4753-9ed7-d3dc8072667b</RequestID></Response>
2016-04-28 23:38:30,488 main ERROR EC2ResponseError: 400 Bad Request
<?xml version="1.0" encoding="UTF-8"?>
<Response><Errors><Error><Code>InvalidGroup.NotFound</Code><Message>The security group 'sg-270fa542' does not exist</Message></Error></Errors><RequestID>718987da-03bd-4753-9ed7-d3dc8072667b</RequestID></Response>
Traceback (most recent call last):
  File "tp.py", line 425, in run
    self.save_money()
  File "tp.py", line 452, in save_money
    self.bid()
  File "tp.py", line 210, in bid
    monitoring_enabled = True)
  File "/usr/lib/python2.7/dist-packages/boto/ec2/connection.py", line 1638, in request_spot_instances
    verb='POST')
  File "/usr/lib/python2.7/dist-packages/boto/connection.py", line 1186, in get_list
    raise self.ResponseError(response.status, response.reason, body)
```

Here's my tp.conf file:
```
{
    "max_price": {
        "t2.micro": "0.200"
    },
    "spot_type": "t2.micro",
    "emergency_type": "t2.micro",
    "max_candidates": 7,
    "instance_name": "thumbor-teste",
    "region": "sa-east-1",
    "placement":  "sa-east-1a",
    "instance_profile_name": "role_baseline",
    "health_check_path": "ping",
    "lower_cpu": 5,
    "upper_cpu": 19,
    "lower_threshold": 1,
    "upper_threshold": 1,
    "tags": {"VREnv":"QA"},
    "user_data_file": null
}
```

Is there anything wrong in my configuration?
Thanks!

**Comment by mwconceicao** [comment]
@wilsonhipolito Hi there! Are you using VPC or EC2-Classic?

**Comment by wilsonhipolito** [comment]
Hi @mwconceicao !
I'm using VPC

**Comment by mwconceicao** [comment]
I'll be merging the PR #8 that adds the VPC support to it :+1:

**Comment by wilsonhipolito** [comment]
Nice! thanks, @mwconceicao ! ❤️

**Comment by mwconceicao** [comment]
@wilsonhipolito PR #8 merged. Check it out please.

**Comment by wilsonhipolito** [comment]
@mwconceicao It works! 👍 
I'll make further tests, but there's no more errors about the security groups. Thanks!
